In [4]:
import numpy as np

a = np.array([[1,2,3,4],
              [5,6,7,8]])

print(a)
print(a.shape)
print(a.dtype)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
int64


In [5]:
import numpy as np

zeros_matrix = np.zeros((3, 4))
print("3x4 matrix of zeros:")
print(zeros_matrix)

ones_matrix = np.ones((2, 5))
print("2x5 matrix of ones:")
print(ones_matrix)

3x4 matrix of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2x5 matrix of ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

reshapedarr = a.reshape(3,4)

print("Original matrix:")
print(a)
print(a.shape)

print("Reshaped matrix:")
print(reshapedarr)
print(reshapedarr.shape)

Original matrix:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
Reshaped matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [8]:
import numpy as np

arr = np.random.randint(0, 151, 10)

print("Array:")
print(arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

Array:
[ 31  97 144  89  21   2  43  56  70  92]
Minimum: 2
Maximum: 144
Mean: 64.5
Sum: 645


In [9]:
import pandas as pd

data = {
    "Student_Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:")
print(df)

print("\nDatatype of each column:")
print(df.dtypes)

DataFrame:
  Student_Name  Marks
0        Alice     85
1          Bob     90
2      Charlie     78
3        David     92

Datatype of each column:
Student_Name      str
Marks           int64
dtype: object


In [10]:
import pandas as pd

df = pd.read_csv("wine.data")

print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

First 5 records:
   1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  3.92  \
0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   

   1065  
0  1050  
1  1185  
2  1480  
3   735  
4  1450  

Last 5 records:
     1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29  5.64  1.04  \
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.7  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.3  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0

In [ ]:
import pandas as pd
# Load dataset
df = pd.read_csv("wine.data")

# Display dataset
print("Dataset:")
print(df)

# Display dataset structure
print("\nDataset Structure (Info):")
df.info()

# Number of rows and columns
rows, cols = df.shape
print(f"\nNumber of rows: {rows}")
print(f"Number of columns: {cols}")

# Check missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

Dataset:
     1  14.23  1.71  2.43  15.6  127   2.8  3.06   .28  2.29   5.64  1.04  \
0    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
1    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
2    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
3    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
4    1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97   6.75  1.05   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

     3.92  1065  
0    3.40  1050  
1    3.17  1185  
2    3.45  1

In [13]:
import pandas as pd

# Column names for Wine dataset
columns = [
    0, 1, 2, 3, 4,
    5, 6, 7, 8,
    9, 10, 11,
    12, 13
]

# Read dataset
df = pd.read_csv("wine.data", header=None, names=columns)


# Statistical summary
print("\nStatistical Summary:")
summary = df.describe()
print(summary)

# Interpretation of statistics
print("\nInterpretation for each feature:")
for col in df.columns:
    print(f"\nColumn: {col}")
    print("Mean:", summary[col]["mean"])
    print("Standard Deviation:", summary[col]["std"])
    print("Minimum Value:", summary[col]["min"])
    print("Maximum Value:", summary[col]["max"])


Statistical Summary:
               0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.295112    2.029270    0.361854    1.590899    5.058090    0.957449   
std  